### ISSUE TITLE
Progress Stuck at 0%

### ISSUE THREAD

**Issue by broadld** [rockandscissor/osid#7]
When you go to http://osid the page displays 0% progress and say "Connecting to image write sub-system.."
I'm not sure how to get rid of this. I have tried a different PC and the same page loads.

Thanks
David

![error](https://cloud.githubusercontent.com/assets/11189789/6367293/111820a4-bcc9-11e4-8600-e3fcfea178be.png)

**Comment by snemetz** [comment]
Did it ever work? Or is this a new install?
If this is a new install, it is probably a permissions issue.
You can look at my fork. I have an install script for Arch there.

**Comment by broadld** [comment]
Hi there,

This has never worked and it is a new install. This is installed on Raspbian with apache2. The image itself is on a usb memory stick that is mounted to the etc/osid/imgroot directory. I had to do this as i do not have a memory card large enough and was trying to get around buying one. Is it possible to do this?

Thanks
David

**Comment by snemetz** [comment]
Should be no problem with USB stick. Just make sure you don't select it to write to. OSID will find it and list it in the devices to write to.
So you have software installed on memory card with the OS and USB stick mounted on /etc/osid/imgroot
Next make sure all the directories have the right permissions, php.ini has been modified for additional paths, and php-fpm has been restarted.
You can look at my script for all this info or there is an older comment that also has this info. Just can't run my script since the package commands would be different for Raspbian. Once you make those changes it should work.

**Comment by broadld** [comment]
Hi there
Could you give me a direct link to the correct permissions and php.ini modifications as i am struggling finding this. This is my first time on GitHub. Trying to get my head around how it works.

Thanks
David

**Comment by snemetz** [comment]
Here's the link to my script https://github.com/snemetz/osid/blob/master/arch_osid_setup.sh
It should have all the info you need. Some commands will be different for Raspbian, but a lot would be the same.

**Comment by broadld** [comment]
What would i need to add into the php.ini file for my setup?
I have checked permissions and they seem fine. I have followed the Raspbian guide word for word. I must be missing something simple.
I get to the page and i can see the image file i can select the devices and i click write image to devices and then it hangs at "Connecting to image writ sub-system..."

**Comment by snemetz** [comment]
The open_basedir lines needs the OSID web, system, and image directories added

**Comment by broadld** [comment]
i have edited this line:-

open_basedir = :/etc/osid/www/public_html/ :/etc/osid/system/ :/etc/osid/imgroot

Is this correct? Do i need to restart apache after this change?

**Comment by snemetz** [comment]
Get rid of the spaces around the colons, then restart php-fpm

**Comment by broadld** [comment]
Ok i have now edited this to:-

open_basedir = :/etc/osid/www/public_html/:/etc/osid/system/:/etc/osid/imgroot

Do i need to remove the space after =?
I also don't think i have php-fpm installed as this is not in the raspbian guide

Thanks
David

**Comment by broadld** [comment]
Can anyone help any further with this as i am completely stuck!

**Comment by snemetz** [comment]
I just got my 7 port hubs and some of the usb to MicroSD adapters. So, I've started to do some more testing.

I've found that the progress monitor web dialog does not always work. So, I recommend tailing the progress.info to see if things are working. Unsure why it works sometimes and not at other times.

**Comment by broadld** [comment]
Hi there,

i have tried sudo tail -f progress.info and it says cannot open is this the correct syntax?
I have browsed to the memory cards and there has been no information copied to them.

Thanks
David
